In [54]:
import os
import pandas as pd
import numpy as np
import seaborn as sns 
import matplotlib
import scipy as sp
import matplotlib.pyplot as plt
from matplotlib import rcParams
from scipy.stats import sem
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import r2_score
from sklearn import linear_model
import statsmodels.api as sm
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR

In [21]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [22]:
master = pd.read_csv('/content/drive/My Drive/HNC/Data/Master_file')
master.head()

,patient_num,replanned_or_not,R_fx,R_fx-determined,R-vs-SHBR,BODY,Body-1,Body-2,Body-3,Body-4,...,neck_area_fx-26,neck_area_fx-27,neck_area_fx-28,neck_area_fx-29,neck_area_fx-30,neck_area_fx-31,neck_area_fx-32,neck_area_fx-33,neck_area_fx-34,neck_area_fx-35
0,19,R,21.0,15.0,r,21.484754,20.805747,NaN,NaN,NaN,...,NaN,NaN,62.0672,NaN,59.0119,NaN,59.6073,NaN,NaN,NaN
1,35,R,26.0,20.0,r,18.636867,21.230902,NaN,19.124266,NaN,...,69.6107,NaN,68.9219,NaN,NaN,68.8933,NaN,NaN,67.8577,NaN
2,115,R,12.0,12.0,shbr,21.957419,21.883293,NaN,NaN,22.405124,...,62.7572,NaN,61.3708,NaN,NaN,60.8830,NaN,62.6707,NaN,NaN
3,272,R,25.0,19.0,r,22.138647,20.795968,NaN,NaN,NaN,...,NaN,62.0832,NaN,NaN,NaN,60.9116,NaN,60.0142,NaN,NaN
4,447,R,23.0,19.0,r,19.842300,21.966858,NaN,NaN,21.909313,...,NaN,NaN,NaN,NaN,NaN,NaN,57.2289,NaN,NaN,NaN

In [23]:
# Keeping only replanned patients
replanned = pd.DataFrame(master.loc[master['replanned_or_not']=='R'])
len(replanned)

31

In [24]:
len(replanned.columns)

420

In [25]:
# Deleting columns with more than 30% null values

for col in replanned.columns:
  if replanned[col].isna().sum() >= 0.3 * len(replanned):
    del replanned[col]
cols = replanned.columns.tolist()
len(cols)

231

In [26]:
# Dropping numerical features with < 3  unique values
for col in replanned.columns:
  if replanned[col].nunique() < 3 and replanned[col].dtype == 'float64':
    print(f"{col} {replanned[col].dtype}: {replanned[col].unique()}\n\n")
    del replanned[col]
cols = replanned.columns.tolist()
len(cols)

volume_outer-PTV_BODY float64: [0.         1.56789567]


volume-ratio_outer-PTV_BODY float64: [0.00000000e+00 7.16429681e-08]


total-dose_prescribed_course float64: [70. nan]


dose_prescribed_fx float64: [ 2. nan]


PEG float64: [ 1.  0. nan]

226

In [27]:
# List of columns having categorical data
obj_df = replanned.select_dtypes(include=['object']).copy()
obj_df.head()

,replanned_or_not,R-vs-SHBR,sex,cancer_category,diagnosis_id,stage_summary,T,N,M,chemo
0,R,r,Male,Oropharyngeal cancer,C01,IVA,T4,N2c,M0,Chemo
1,R,r,Female,Oropharyngeal cancer,C09.9,IVA,T4,N2c,M0,Chemo
2,R,shbr,Male,Nasopharyngeal Cancer,C11.9,III,T1,N2,M0,Chemo
3,R,r,Male,Oropharyngeal cancer,C01,X,T2,N2b,M0,Chemo
4,R,r,Male,Oropharyngeal cancer,C01,X,T2,N3,MX,Chemo

In [28]:
# List of columns having numerical data
num_df = replanned.select_dtypes(include=['int64','float64']).copy()
num_df.head()

,patient_num,R_fx,R_fx-determined,BODY,Body-1,Body-6,xmin-slope_Body-1,xmin-slope_Body-2,xmin-slope_Body-3,xmin-slope_Body-4,...,volume-ratio-slope_outer-PTV_Body-23,volume-ratio-slope_outer-PTV_Body-24,volume-ratio-slope_outer-PTV_Body-25,volume-ratio-slope_outer-PTV_Body-26,age_start,cancer_category_id,num_chemo,first_weight_kg,total_weight-loss_kg,neck_area_fx-1
0,19,21.0,15.0,21.484754,20.805747,20.842635,-5.599176,-5.599176,-5.599176,-5.599176,...,0.000282,0.000282,0.000282,0.000282,56.5421,2.0,3.0,99.3,12.7895,70.5077
1,35,26.0,20.0,18.636867,21.230902,17.781444,-3.322000,-3.322000,-0.553786,-0.553786,...,0.000014,0.000014,0.000014,0.000014,54.1246,2.0,3.0,64.7,10.6646,63.9857
2,115,12.0,12.0,21.957419,21.883293,21.081882,-1.557421,-1.557421,-1.557421,-0.319167,...,0.000011,0.000007,0.000007,0.000004,49.8700,4.0,3.0,69.5,12.5180,67.4203
3,272,25.0,19.0,22.138647,20.795968,18.100129,-6.803470,-6.803470,-6.803470,-6.803470,...,0.000568,0.000568,0.000568,0.000568,68.2574,2.0,3.0,98.7,10.5370,70.6577
4,447,23.0,19.0,19.842300,21.966858,NaN,-4.473957,-4.473957,-4.473957,-0.970603,...,0.000405,0.000405,0.000405,0.000405,65.0157,2.0,3.0,72.0,4.0278,76.4357

In [29]:
# Filled Nan with mode
print(replanned['cancer_category_id'].value_counts())
replanned['cancer_category_id'].fillna(replanned['cancer_category_id'].mode()[0],inplace=True)
print(replanned['cancer_category_id'].isna().sum())

2.0    20
4.0     5
5.0     2
1.0     1
9.0     1
Name: cancer_category_id, dtype: int64
0

In [30]:
# filling numerical variables with median
for col in num_df.columns:
  if replanned[col].isna().sum() > 0:
    print(f"{col} {replanned[col].dtype}: {replanned[col].isna().sum()}" )
    replanned[col].fillna(replanned[col].median(),inplace=True)
    print(f"{col} {replanned[col].dtype}: {replanned[col].isna().sum()}" )

Body-6 float64: 9
Body-6 float64: 0
volume_body_Body-6 float64: 9
volume_body_Body-6 float64: 0
volume_outer-PTV_Body-6 float64: 9
volume_outer-PTV_Body-6 float64: 0
volume-ratio_inner-PTV_Body-6 float64: 9
volume-ratio_inner-PTV_Body-6 float64: 0
volume-ratio_outer-PTV_Body-6 float64: 9
volume-ratio_outer-PTV_Body-6 float64: 0
age_start float64: 2
age_start float64: 0
num_chemo float64: 2
num_chemo float64: 0
first_weight_kg float64: 2
first_weight_kg float64: 0
total_weight-loss_kg float64: 2
total_weight-loss_kg float64: 0
neck_area_fx-1 float64: 8
neck_area_fx-1 float64: 0

In [31]:
# filling categorical variables with mode
for col in obj_df.columns:
  if replanned[col].isna().sum() > 0:
    print(f"{col} {replanned[col].dtype}: {replanned[col].isna().sum()}" )
    replanned[col].fillna(replanned[col].mode()[0],inplace=True)
    print(f"{col} {replanned[col].dtype}: {replanned[col].isna().sum()}" )

sex object: 2
sex object: 0
cancer_category object: 2
cancer_category object: 0
diagnosis_id object: 2
diagnosis_id object: 0
stage_summary object: 2
stage_summary object: 0
T object: 2
T object: 0
N object: 2
N object: 0
M object: 2
M object: 0
chemo object: 2
chemo object: 0

In [32]:
for col in obj_df:
  replanned[col] = replanned[col].astype('category')
  replanned[col] = replanned[col].cat.codes
replanned.head()

,patient_num,replanned_or_not,R_fx,R_fx-determined,R-vs-SHBR,BODY,Body-1,Body-6,xmin-slope_Body-1,xmin-slope_Body-2,...,diagnosis_id,stage_summary,T,N,M,chemo,num_chemo,first_weight_kg,total_weight-loss_kg,neck_area_fx-1
0,19,0,21.0,15.0,0,21.484754,20.805747,20.842635,-5.599176,-5.599176,...,0,2,3,4,0,0,3.0,99.3,12.7895,70.5077
1,35,0,26.0,20.0,0,18.636867,21.230902,17.781444,-3.322000,-3.322000,...,4,2,3,4,0,0,3.0,64.7,10.6646,63.9857
2,115,0,12.0,12.0,1,21.957419,21.883293,21.081882,-1.557421,-1.557421,...,6,1,0,2,0,0,3.0,69.5,12.5180,67.4203
3,272,0,25.0,19.0,0,22.138647,20.795968,18.100129,-6.803470,-6.803470,...,0,6,1,3,0,0,3.0,98.7,10.5370,70.6577
4,447,0,23.0,19.0,0,19.842300,21.966858,20.461444,-4.473957,-4.473957,...,0,6,1,5,2,0,3.0,72.0,4.0278,76.4357

In [33]:
cols = replanned.columns.tolist()
list(enumerate(cols))

[(0, 'patient_num'),
 (1, 'replanned_or_not'),
 (2, 'R_fx'),
 (3, 'R_fx-determined'),
 (4, 'R-vs-SHBR'),
 (5, 'BODY'),
 (6, 'Body-1'),
 (7, 'Body-6'),
 (8, 'xmin-slope_Body-1'),
 (9, 'xmin-slope_Body-2'),
 (10, 'xmin-slope_Body-3'),
 (11, 'xmin-slope_Body-4'),
 (12, 'xmin-slope_Body-5'),
 (13, 'xmin-slope_Body-6'),
 (14, 'xmin-slope_Body-7'),
 (15, 'xmin-slope_Body-8'),
 (16, 'xmin-slope_Body-9'),
 (17, 'xmin-slope_Body-10'),
 (18, 'xmin-slope_Body-11'),
 (19, 'xmin-slope_Body-12'),
 (20, 'xmin-slope_Body-13'),
 (21, 'xmin-slope_Body-14'),
 (22, 'xmin-slope_Body-15'),
 (23, 'xmin-slope_Body-16'),
 (24, 'xmin-slope_Body-17'),
 (25, 'xmin-slope_Body-18'),
 (26, 'xmin-slope_Body-19'),
 (27, 'xmin-slope_Body-20'),
 (28, 'xmin-slope_Body-21'),
 (29, 'xmin-slope_Body-22'),
 (30, 'xmin-slope_Body-23'),
 (31, 'xmin-slope_Body-24'),
 (32, 'xmin-slope_Body-25'),
 (33, 'xmin-slope_Body-26'),
 (34, 'res-vector_x'),
 (35, 'res-vector_y'),
 (36, 'res-vector_z'),
 (37, 'res-vector_radial'),
 (38, 'res-vector_polar'),
 (39, 'res-vector_azimuthal'),
 (40, 'CoM_x'),
 (41, 'CoM_y'),
 (42, 'CoM_z'),
 (43, 'CoM_rbound-2D'),
 (44, 'CoM_rbound-3D'),
 (45, 'limits_mid_x'),
 (46, 'limits_mid_y'),
 (47, 'limits_mid_z'),
 (48, 'limits_rbound-2D'),
 (49, 'limits_rbound-3D'),
 (50, 'xmed-slope_Body-1'),
 (51, 'xmed-slope_Body-2'),
 (52, 'xmed-slope_Body-3'),
 (53, 'xmed-slope_Body-4'),
 (54, 'xmed-slope_Body-5'),
 (55, 'xmed-slope_Body-6'),
 (56, 'xmed-slope_Body-7'),
 (57, 'xmed-slope_Body-8'),
 (58, 'xmed-slope_Body-9'),
 (59, 'xmed-slope_Body-10'),
 (60, 'xmed-slope_Body-11'),
 (61, 'xmed-slope_Body-12'),
 (62, 'xmed-slope_Body-13'),
 (63, 'xmed-slope_Body-14'),
 (64, 'xmed-slope_Body-15'),
 (65, 'xmed-slope_Body-16'),
 (66, 'xmed-slope_Body-17'),
 (67, 'xmed-slope_Body-18'),
 (68, 'xmed-slope_Body-19'),
 (69, 'xmed-slope_Body-20'),
 (70, 'xmed-slope_Body-21'),
 (71, 'xmed-slope_Body-22'),
 (72, 'xmed-slope_Body-23'),
 (73, 'xmed-slope_Body-24'),
 (74, 'xmed-slope_Body-25'),
 (75, 'xmed-slope_Body-26'),
 (76, 'xave-slope_Body-1'),
 (77, 'xave-slope_Body-2'),
 (78, 'xave-slope_Body-3'),
 (79, 'xave-slope_Body-4'),
 (80, 'xave-slope_Body-5'),
 (81, 'xave-slope_Body-6'),
 (82, 'xave-slope_Body-7'),
 (83, 'xave-slope_Body-8'),
 (84, 'xave-slope_Body-9'),
 (85, 'xave-slope_Body-10'),
 (86, 'xave-slope_Body-11'),
 (87, 'xave-slope_Body-12'),
 (88, 'xave-slope_Body-13'),
 (89, 'xave-slope_Body-14'),
 (90, 'xave-slope_Body-15'),
 (91, 'xave-slope_Body-16'),
 (92, 'xave-slope_Body-17'),
 (93, 'xave-slope_Body-18'),
 (94, 'xave-slope_Body-19'),
 (95, 'xave-slope_Body-20'),
 (96, 'xave-slope_Body-21'),
 (97, 'xave-slope_Body-22'),
 (98, 'xave-slope_Body-23'),
 (99, 'xave-slope_Body-24'),
 (100, 'xave-slope_Body-25'),
 (101, 'xave-slope_Body-26'),
 (102, 'volume_body_BODY'),
 (103, 'volume_body_Body-1'),
 (104, 'volume_body_Body-6'),
 (105, 'volume-slope_body_Body-2'),
 (106, 'volume-slope_body_Body-3'),
 (107, 'volume-slope_body_Body-4'),
 (108, 'volume-slope_body_Body-5'),
 (109, 'volume-slope_body_Body-6'),
 (110, 'volume-slope_body_Body-7'),
 (111, 'volume-slope_body_Body-8'),
 (112, 'volume-slope_body_Body-9'),
 (113, 'volume-slope_body_Body-10'),
 (114, 'volume-slope_body_Body-11'),
 (115, 'volume-slope_body_Body-12'),
 (116, 'volume-slope_body_Body-13'),
 (117, 'volume-slope_body_Body-14'),
 (118, 'volume-slope_body_Body-15'),
 (119, 'volume-slope_body_Body-16'),
 (120, 'volume-slope_body_Body-17'),
 (121, 'volume-slope_body_Body-18'),
 (122, 'volume-slope_body_Body-19'),
 (123, 'volume-slope_body_Body-20'),
 (124, 'volume-slope_body_Body-21'),
 (125, 'volume-slope_body_Body-22'),
 (126, 'volume-slope_body_Body-23'),
 (127, 'volume-slope_body_Body-24'),
 (128, 'volume-slope_body_Body-25'),
 (129, 'volume-slope_body_Body-26'),
 (130, 'volume_outer-PTV_Body-1'),
 (131, 'volume_outer-PTV_Body-6'),
 (132, 'volume-slope_outer-PTV_Body-2'),
 (133, 'volume-slope_outer-PTV_Body-3'),
 (134, 'volume-slope_outer-PTV_Body-4'),
 (135, 'volume-slope_outer-PTV_Body-5'),
 (136, 'volume-slope_outer-PTV_Body-6'),
 (137, 'volume-slope_outer-PTV_Body-7'),
 (138, 'volume-slope_outer-PTV_Body-8'),
 (139, 'volume-slope_outer-PTV_Body-9'),
 (140, 'volume-slope_outer-PTV_Body-10'),
 (141, 'volume-slope_outer-PTV_Body-11'),
 (142, 'volume-slope_outer-PTV_Body-12'),
 (143, 'volume-slope_outer-PTV_Body-13'),
 (144, 'volume-slope_outer-PTV_Body-14'),
 (145, 'volume-slope_outer-PTV_Body-15'),
 (146, 'volume-slope_outer-PTV_Body-16'),
 (147, 'volume-slope_outer-PTV_Body-17'),
 (148, 'volume-slope_outer-PTV_Body-18'),
 (149, 'volume-slope_outer-PTV_Body-19'),
 (150, 'volume-slope_outer-PTV_Body-20'),
 (151, 'volume-slope_outer-PTV_Body-21'),
 (152, 'volume-slope_outer-PTV_Body-22'),
 (153, 'volume-slope_outer-PTV_Body-23'),
 (154, 'volume-slope_outer-PTV_Body-24'),
 (155, 'volume-slope_outer-PTV_Body-25'),
 (156, 'volume-slope_outer-PTV_Body-26'),
 (157, 'volume-ratio_inner-PTV_BODY'),
 (158, 'volume-ratio_inner-PTV_Body-1'),
 (159, 'volume-ratio_inner-PTV_Body-6'),
 (160, 'volume-ratio-slope_inner-PTV_Body-2'),
 (161, 'volume-ratio-slope_inner-PTV_Body-3'),
 (162, 'volume-ratio-slope_inner-PTV_Body-4'),
 (163, 'volume-ratio-slope_inner-PTV_Body-5'),
 (164, 'volume-ratio-slope_inner-PTV_Body-6'),
 (165, 'volume-ratio-slope_inner-PTV_Body-7'),
 (166, 'volume-ratio-slope_inner-PTV_Body-8'),
 (167, 'volume-ratio-slope_inner-PTV_Body-9'),
 (168, 'volume-ratio-slope_inner-PTV_Body-10'),
 (169, 'volume-ratio-slope_inner-PTV_Body-11'),
 (170, 'volume-ratio-slope_inner-PTV_Body-12'),
 (171, 'volume-ratio-slope_inner-PTV_Body-13'),
 (172, 'volume-ratio-slope_inner-PTV_Body-14'),
 (173, 'volume-ratio-slope_inner-PTV_Body-15'),
 (174, 'volume-ratio-slope_inner-PTV_Body-16'),
 (175, 'volume-ratio-slope_inner-PTV_Body-17'),
 (176, 'volume-ratio-slope_inner-PTV_Body-18'),
 (177, 'volume-ratio-slope_inner-PTV_Body-19'),
 (178, 'volume-ratio-slope_inner-PTV_Body-20'),
 (179, 'volume-ratio-slope_inner-PTV_Body-21'),
 (180, 'volume-ratio-slope_inner-PTV_Body-22'),
 (181, 'volume-ratio-slope_inner-PTV_Body-23'),
 (182, 'volume-ratio-slope_inner-PTV_Body-24'),
 (183, 'volume-ratio-slope_inner-PTV_Body-25'),
 (184, 'volume-ratio-slope_inner-PTV_Body-26'),
 (185, 'volume-ratio_outer-PTV_Body-1'),
 (186, 'volume-ratio_outer-PTV_Body-6'),
 (187, 'volume-ratio-slope_outer-PTV_Body-2'),
 (188, 'volume-ratio-slope_outer-PTV_Body-3'),
 (189, 'volume-ratio-slope_outer-PTV_Body-4'),
 (190, 'volume-ratio-slope_outer-PTV_Body-5'),
 (191, 'volume-ratio-slope_outer-PTV_Body-6'),
 (192, 'volume-ratio-slope_outer-PTV_Body-7'),
 (193, 'volume-ratio-slope_outer-PTV_Body-8'),
 (194, 'volume-ratio-slope_outer-PTV_Body-9'),
 (195, 'volume-ratio-slope_outer-PTV_Body-10'),
 (196, 'volume-ratio-slope_outer-PTV_Body-11'),
 (197, 'volume-ratio-slope_outer-PTV_Body-12'),
 (198, 'volume-ratio-slope_outer-PTV_Body-13'),
 (199, 'volume-ratio-slope_outer-PTV_Body-14'),
 (200, 'volume-ratio-slope_outer-PTV_Body-15'),
 (201, 'volume-ratio-slope_outer-PTV_Body-16'),
 (202, 'volume-ratio-slope_outer-PTV_Body-17'),
 (203, 'volume-ratio-slope_outer-PTV_Body-18'),
 (204, 'volume-ratio-slope_outer-PTV_Body-19'),
 (205, 'volume-ratio-slope_outer-PTV_Body-20'),
 (206, 'volume-ratio-slope_outer-PTV_Body-21'),
 (207, 'volume-ratio-slope_outer-PTV_Body-22'),
 (208, 'volume-ratio-slope_outer-PTV_Body-23'),
 (209, 'volume-ratio-slope_outer-PTV_Body-24'),
 (210, 'volume-ratio-slope_outer-PTV_Body-25'),
 (211, 'volume-ratio-slope_outer-PTV_Body-26'),
 (212, 'sex'),
 (213, 'age_start'),
 (214, 'cancer_category'),
 (215, 'cancer_category_id'),
 (216, 'diagnosis_id'),
 (217, 'stage_summary'),
 (218, 'T'),
 (219, 'N'),
 (220, 'M'),
 (221, 'chemo'),
 (222, 'num_chemo'),
 (223, 'first_weight_kg'),
 (224, 'total_weight-loss_kg'),
 (225, 'neck_area_fx-1')]

In [34]:
# Deleting data after 12th fraction
for i in range(13,27):
  del replanned[f'xmin-slope_Body-{i}']
  del replanned[f'xmed-slope_Body-{i}']
  del replanned[f'xave-slope_Body-{i}']
  del replanned[f'volume-slope_body_Body-{i}']
  del replanned[f'volume-slope_outer-PTV_Body-{i}']
  del replanned[f'volume-ratio-slope_inner-PTV_Body-{i}']
  del replanned[f'volume-ratio-slope_outer-PTV_Body-{i}']

In [35]:
# Deleting replanned_or_not column because we are only using replanned data here
del replanned['replanned_or_not']

In [36]:
# Creating the input of training and testing data
Rx = replanned.copy()
del Rx['patient_num']
del Rx['R_fx-determined']
Rx.head()

,R_fx,R-vs-SHBR,BODY,Body-1,Body-6,xmin-slope_Body-1,xmin-slope_Body-2,xmin-slope_Body-3,xmin-slope_Body-4,xmin-slope_Body-5,...,diagnosis_id,stage_summary,T,N,M,chemo,num_chemo,first_weight_kg,total_weight-loss_kg,neck_area_fx-1
0,21.0,0,21.484754,20.805747,20.842635,-5.599176,-5.599176,-5.599176,-5.599176,-5.599176,...,0,2,3,4,0,0,3.0,99.3,12.7895,70.5077
1,26.0,0,18.636867,21.230902,17.781444,-3.322000,-3.322000,-0.553786,-0.553786,-0.553786,...,4,2,3,4,0,0,3.0,64.7,10.6646,63.9857
2,12.0,1,21.957419,21.883293,21.081882,-1.557421,-1.557421,-1.557421,-0.319167,-0.319167,...,6,1,0,2,0,0,3.0,69.5,12.5180,67.4203
3,25.0,0,22.138647,20.795968,18.100129,-6.803470,-6.803470,-6.803470,-6.803470,-6.803470,...,0,6,1,3,0,0,3.0,98.7,10.5370,70.6577
4,23.0,0,19.842300,21.966858,20.461444,-4.473957,-4.473957,-4.473957,-0.970603,-1.415517,...,0,6,1,5,2,0,3.0,72.0,4.0278,76.4357

In [38]:
# Data Split
# dividing into 70%(train) and 30%(test)
X_train, X_test, y_train, y_test = train_test_split(Rx, Ry, test_size=0.3)
X_train.shape, y_train.shape

((21, 125), (21, 1))

In [50]:
names = ["Random_Forest", "Decesion_Tree","SVR"]

regressors = [
    RandomForestRegressor(),
    DecisionTreeRegressor(),
    SVR(),
    ]

In [51]:
scores = []
for name, clf in zip(names, regressors):
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    score = r2_score(y_test,y_pred)
    scores.append(score)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [52]:
scores

[-0.07180289672544093, -2.243073047858942, -0.01450118643912579]